# Generated by Django 5.2.8 on 2025-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbuser',
            name='userAvatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pbuser',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
