# Generated by Django 5.2.8 on 2025-11-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pbuser_useravatar_alter_pbuser_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbuser',
            name='admin',
        ),
    ]
