# Generated by Django 5.2.8 on 2025-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_pbuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbuser',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
