# Generated by Django 5.2.8 on 2025-11-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pbuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbuser',
            old_name='userAvatar',
            new_name='user_avatar',
        ),
    ]
