# Generated by Django 5.2.8 on 2025-11-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_useravatar_pbuser_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbuser',
            name='admin',
        ),
    ]
