# Generated by Django 6.0 on 2025-12-05 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Services title')),
                ('short_description', models.CharField(help_text='Description')),
                ('service_keypoints', models.CharField(help_text='Services keypoints')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Services title')),
                ('short_description', models.CharField(help_text='Description')),
                ('service_keypoints', models.CharField(help_text='Services keypoints')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOffers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Provide package offer.', max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='datalib.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPackages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Provide a package name e.g Starter, Standard, Growth', max_length=100)),
                ('description', models.CharField(default='no description', help_text='provide offers description', max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serivece_packages', to='datalib.services')),
                ('service_keypoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_keypoints', to='datalib.servicesoffers')),
            ],
        ),
    ]
