# Generated by Django 6.0 on 2025-12-05 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespackages',
            name='service_keypoints',
        ),
        migrations.AddField(
            model_name='servicespackages',
            name='max_price',
            field=models.FloatField(default=0.0, help_text='Provide pricing for the package'),
        ),
        migrations.AddField(
            model_name='servicespackages',
            name='min_price',
            field=models.FloatField(default=0.0, help_text='Provide pricing for the package'),
        ),
        migrations.AlterField(
            model_name='servicespackages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='datalib.services'),
        ),
        migrations.CreateModel(
            name='ServicesMainKeyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Provide package offer.', max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_main_keypoints', to='datalib.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSubKeyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Provide package offer.', max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sub_keypoints', to='datalib.services')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicesOffers',
        ),
    ]
