# Generated by Django 6.0 on 2025-12-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0002_remove_servicespackages_service_keypoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_keypoints',
        ),
    ]
