# Generated by Django 6.0 on 2025-12-05 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0003_remove_services_service_keypoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesSubKeyPoints',
            new_name='PackagesKeyPoints',
        ),
        migrations.AlterField(
            model_name='packageskeypoints',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sub_keypoints', to='datalib.servicespackages'),
        ),
    ]
