# Generated by Django 6.0 on 2025-12-05 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0004_rename_servicessubkeypoints_packageskeypoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Provide package offer.', max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_list', to='datalib.servicespackages')),
            ],
        ),
    ]
